
model:
  psz: 15
  model_fname: "models/feb402psz15.pth"

frame:
  dark_h5: null
  min_intensity: 100
  offset_recover: 0 # a[a>0] += offset_recover
  pvkey: "1id-ADSim2:Pva1:Image"
  nproc: 2 # number of processes for frame preproc
  max_radius: 3000
  min_peak_sz: 3 # minimum number of non-pixel
  datatype: "ushortValue" # only if data are not compressed
  
infer:
  tensorrt: False
  mbsz: 121

output:
  #frame2file: "/net/wolf/data/users/zhengchun.liu/frames.h5"
  #peaks2file: "/net/wolf/data/users/zhengchun.liu/peaks.h5"
  frame2file: null
  peaks2file: null
  port4zmq: 5678
  chkey: "edgeBraggNN:PVA" # pva output channel name
  freq: 200
